# workflowの名前
name: Sample actions

# トリガーの設定
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 実行環境の設定

    steps:
      - uses: actions/checkout@v2

      # git diffをするためにターゲットブランチをフェッチする
      - name: Fetch
        run: |
          git fetch --depth 1 origin ${GITHUB_BASE_REF}
          git fetch --depth 1 origin ${GITHUB_HEAD_REF}

      - name: CodeCheck
        run: |
          for f in $(git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --diff-filter=A --name-only) ; do
          echo "A"
          echo $f
          done

          for f in $(git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --diff-filter=M --name-only) ; do
          echo "M"
          echo $f
          done
      
      - name: AddReviewer
        env:
          REVIEWERS: "nakatomo3"
        run: |
          reviewer_count=$(cat ${{ github.event_path }} | jq '.pull_request.requested_reviewers | length')
          if [[ 0 == $reviewer_count ]]; then
            reviewers=$(echo "\"${REVIEWERS// /}\"" | jq 'split(",") | .-["${{ github.actor }}"]')
            curl -X POST \
                 -H "Content-Type: application/json" \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d "{ \"reviewers\": $reviewers }" \
                 https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          fi
